# Uygulama İsmi
spring.application.name=hastane-randevu-sistemi

# H2 Veritabanı Ayarları
spring.datasource.url=jdbc:h2:mem:hastanedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# H2 Konsolunu Aktif Et (Tarayıcıdan bakabilmek için)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# SQL Sorgularını Konsolda Gör (Hata ayıklamak için)
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
